version: '3.8'

services:
  backup_manager:
    container_name: backup_manager
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - ../../:/source/backup_manager
      - ./backup_manager/configs:/opt/backup_manager/configs
      - ./backup_manager/backups:/opt/backup_manager/backups
    working_dir: /source/backup_manager/backup_manager_csharp
    command: tail -f /dev/null