version: '3.8'

services:
  backup_manager:
    container_name: BackupManager
    image: ubuntu:latest
    volumes:
      - ../../:/source/BackupManager
    working_dir: /source/BackupManager/backup_manager_csharp
    command: /bin/bash -c "apt-get update && apt-get install -y wget && wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb && dpkg -i packages-microsoft-prod.deb && apt-get update && apt-get install -y dotnet-sdk-8.0 && /bin/bash"